CREATE TABLE IF NOT EXISTS public.authorities
(
    id         int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "identity" text                                                                                                                     NULL,
    uid        int8                                                                                                                     NOT NULL,
    CONSTRAINT authorities_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.budgets (
                                              budget_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                              owner_profile_id int8 NULL,
                                              created_at timestamptz DEFAULT now() NOT NULL,
                                              monthly_limit numeric DEFAULT '0'::numeric NOT NULL,
                                              daily_limit numeric NULL,
                                              period_first_day date NOT NULL,
                                              CONSTRAINT budget_check CHECK (((daily_limit > (0)::numeric) AND (daily_limit <= monthly_limit))),
                                              CONSTRAINT budget_monthly_limit_check CHECK (((monthly_limit > (0)::numeric) AND (monthly_limit < (100000000)::numeric))),
                                              CONSTRAINT budget_period_first_day_check CHECK ((period_first_day > '2026-01-01'::date)),
                                              CONSTRAINT budget_pkey PRIMARY KEY (budget_id)
);

CREATE TABLE IF NOT EXISTS public.families (
                                               family_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                               owner_id int8 NOT NULL,
                                               family_name text DEFAULT 'Happy Family'::text NOT NULL,
                                               created_at timestamptz DEFAULT now() NOT NULL,
                                               CONSTRAINT families_pkey PRIMARY KEY (family_id)
);

CREATE TABLE IF NOT EXISTS public.profiles (
                                               profile_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                               user_id int8 NOT NULL,
                                               avatar_url text DEFAULT 'https://hlgvugiuwrwkdvvtisms.supabase.co/storage/v1/object/public/public_assets/piggy-bank.svg'::text NULL,
                                               nickname text DEFAULT 'New user'::text NOT NULL,
                                               bio text NULL,
                                               is_profile_public bool DEFAULT false NOT NULL,
                                               family_id int8 NULL,
                                               CONSTRAINT profiles_bio_check CHECK ((length(bio) <= 300)),
                                               CONSTRAINT profiles_nickname_check CHECK ((length(nickname) <= 30)),
                                               CONSTRAINT profiles_pkey PRIMARY KEY (profile_id)
);

CREATE TABLE IF NOT EXISTS public.users (
                                            id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                            username text NOT NULL,
                                            "password" text NOT NULL,
                                            created_at timestamptz DEFAULT now() NOT NULL,
                                            CONSTRAINT users_pkey PRIMARY KEY (id),
                                            CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE public.authorities
    ADD CONSTRAINT authorities_uid_fkey FOREIGN KEY (uid) REFERENCES public.users (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public.budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budgets ADD CONSTRAINT budget_owner_profile_id_fkey FOREIGN KEY (owner_profile_id) REFERENCES public.profiles(profile_id) ON DELETE CASCADE;
ALTER TABLE public.families ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.families ADD CONSTRAINT families_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(profile_id);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_family_id_fkey FOREIGN KEY (family_id) REFERENCES public.families(family_id) ON DELETE SET NULL;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
