DROP TABLE IF EXISTS public.budgets;

CREATE TABLE public.family_budgets
(
    budget_id        int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at       timestamptz DEFAULT now()                                                                                                NOT NULL,
    monthly_budget   numeric     DEFAULT '0'::numeric                                                                                         NOT NULL,
    daily_limit      numeric                                                                                                                  NULL,
    period_first_day date                                                                                                                     NOT NULL,
    family_id        int8                                                                                                                     NOT NULL,
    budget_left      numeric                                                                                                                  NOT NULL,
    CONSTRAINT budget_check CHECK (((daily_limit > (0)::numeric) AND (daily_limit <= monthly_budget))),
    CONSTRAINT budget_monthly_limit_check CHECK (((monthly_budget > (0)::numeric) AND
                                                  (monthly_budget < (100000000)::numeric))),
    CONSTRAINT budget_period_first_day_check CHECK ((period_first_day > '2026-01-01'::date)),
    CONSTRAINT budget_pkey PRIMARY KEY (budget_id),
    CONSTRAINT chk_daily_limit_le_monthly_budget CHECK ((daily_limit <= monthly_budget))
);

CREATE TABLE public.personal_budgets
(
    id               int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at       timestamptz DEFAULT now()                                                                                                NOT NULL,
    user_id          int8                                                                                                                     NOT NULL,
    monthly_budget   numeric     DEFAULT '0'::numeric                                                                                         NOT NULL,
    daily_limit      numeric     DEFAULT '0'::numeric                                                                                         NULL,
    period_first_day date                                                                                                                     NOT NULL,
    budget_left      numeric                                                                                                                  NOT NULL,
    CONSTRAINT chk_daily_limit_le_monthly_budget CHECK ((daily_limit <= monthly_budget)),
    CONSTRAINT personal_budgets_monthly_budget_check CHECK (((monthly_budget > (0)::numeric) AND
                                                             (monthly_budget < (100000000)::numeric))),
    CONSTRAINT personal_budgets_period_first_day_check CHECK ((period_first_day > '2026-01-01'::date)),
    CONSTRAINT personal_budgets_pkey PRIMARY KEY (id)
);

CREATE TABLE public.spendings
(
    id              int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    user_id         int8                                                                                                                     NULL,
    amount          numeric                                                                                                                  NOT NULL,
    category        text                                                                                                                     NOT NULL,
    notes           text                                                                                                                     NULL,
    created_at      timestamptz DEFAULT now()                                                                                                NOT NULL,
    budget_left_now numeric                                                                                                                  NULL,
    CONSTRAINT spendings_pkey PRIMARY KEY (id)
);

CREATE TABLE public.token_blacklist
(
    id         int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    jti        text                                                                                                                     NOT NULL,
    expires_at timestamptz                                                                                                              NOT NULL,
    CONSTRAINT token_blacklist_pkey PRIMARY KEY (id),
    CONSTRAINT token_blacklist_token_key UNIQUE (jti)
);

ALTER TABLE public.spendings
    ADD CONSTRAINT spendings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE;
ALTER TABLE public.family_budgets
    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.family_budgets
    ADD CONSTRAINT family_budgets_family_id_fkey FOREIGN KEY (family_id) REFERENCES public.families (family_id) ON DELETE CASCADE;
ALTER TABLE public.personal_budgets
    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.personal_budgets
    ADD CONSTRAINT personal_budgets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE;
ALTER TABLE public.spendings
    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.token_blacklist
    ENABLE ROW LEVEL SECURITY;
